// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaYUKXdNrumYOZN9P9n-geMkNwY2ZFuSI',
    appId: '1:99362449868:web:781c80e725485d563b5569',
    messagingSenderId: '99362449868',
    projectId: 'radio-e10ae',
    authDomain: 'radio-e10ae.firebaseapp.com',
    storageBucket: 'radio-e10ae.appspot.com',
    measurementId: 'G-V5MEVQZNVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjhfrZ_0M2KaGc9TMXh3jcF8CalHgw8BA',
    appId: '1:99362449868:android:2b1509b3901e9a033b5569',
    messagingSenderId: '99362449868',
    projectId: 'radio-e10ae',
    storageBucket: 'radio-e10ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4scA803k46Zwl6Z5Nf_TlKwK9neAYt0w',
    appId: '1:99362449868:ios:604d01b94cd357b23b5569',
    messagingSenderId: '99362449868',
    projectId: 'radio-e10ae',
    storageBucket: 'radio-e10ae.appspot.com',
    iosBundleId: 'com.devwizards.globalGroove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4scA803k46Zwl6Z5Nf_TlKwK9neAYt0w',
    appId: '1:99362449868:ios:ad149a3be9482f4b3b5569',
    messagingSenderId: '99362449868',
    projectId: 'radio-e10ae',
    storageBucket: 'radio-e10ae.appspot.com',
    iosBundleId: 'com.devwizards.globalGroove.RunnerTests',
  );
}
